[project]
name = "telegram_bot"
version = "0.1.0"
description = "Telegram bot for group protection with math challenges"
requires-python = ">=3.9"  # Python 3.9+ for better async support and type hints

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta" 